embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
aggr_mode: ['add']
learning_rate: [1e-4]
reg_weight: [1e-4]
hyper_parameters: ["aggr_mode", "reg_weight", "learning_rate"]