# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating

filter_out_cod_start_users: True

inter_file_name: 'amazon.inter'

# name of features

text_feature_file: 'text_feat.npy'
vision_feature_file: None


field_separator: "\t"
